### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by alexpchin** [appmotion/apollo-augmented-hooks#18] opened 2022-05-19 08:37 UTC
I've just begun to experiment with switching over from @apollo/client. I've changed `useQuery` across and am getting `Cannot read property 'filter' of undefined`.

```
variableDefinitions: definition.variableDefinitions.filter(function (_ref3) {

reducedQueries.js (231.28)
````

**Comment by mindnektar** [comment] 2022-05-19 13:00
Hi there! Would you mind giving me an example query that is throwing this error? Then I can add it to the unit tests and provide you with a fix.

**Comment by alexpchin** [comment] 2022-05-20 09:47
Hi @mindnektar Am I right in thinking that this package doesn't work for react-native?

**Comment by mindnektar** [comment] 2022-05-20 11:55
I've never tested it with `react-native`, so I'm afraid I can't answer that question. I'd naively assume that it probably should, since it's little more than a wrapper for `@apollo/client` and that does support it, but I can't be sure. If you give me a failing query, I can see if it works in the test suite, though.

**Comment by mindnektar** [comment] 2022-05-30 08:01
@alexpchin I'm happy to support you if you give me an example query. Otherwise I'm going to have to close this issue since I cannot reproduce it.

**Closed** 2022-06-30 14:00 UTC
